#!/bin/bash
#SBATCH --job-name=gr
#SBATCH -n 36 # Number of cores requested
#SBATCH -t 8:00:00 # Runtime in minutes
#SBATCH -p shared,test # Partition to submit to
#SBATCH --mem-per-cpu=5000 # Memory per cpu in MB (see also--mem)
#SBATCH -o job_%j.out # Standard out goes to this file
#SBATCH -e job_%j.err # Standard err goes to this file
#SBATCH --account=cs205

module load intel/17.0.4-fasrc01 
module load impi/2017.2.174-fasrc01

module list

cp POSCAR_Gr POSCAR
phonopy --dim="3 3 1" -d -c POSCAR-unit # creates a structural file of the supercell and phonopy_disp.yaml (for phonon calculation in phonopy)
cp POSCAR-001 POSCAR
mpirun -np $SLURM_NTASKS ./vasp.std

