#!/bin/bash
#SBATCH -n 16 # Number of cores requested
#SBATCH -t 2-00:00 # Runtime in minutes
#SBATCH -p shared # Partition to submit to
#SBATCH --mem-per-cpu=7100 # Memory per cpu in MB (see also--mem)
#SBATCH -o job_%j.out # Standard out goes to this file
#SBATCH -e job_%j.err # Standard err goes to this file
#SBATCH --account=cs205


module load intel/17.0.4-fasrc01 
module load impi/2017.2.174-fasrc01
module list 

source params.conf
mpirun -n $SLURM_NTASKS $VASP1_FILEPATH
