#!/bin/bash
#SBATCH --job-name=relax
#SBATCH -n 4 # Number of cores requested
#SBATCH -t 0-08:00 # Runtime in minutes
#SBATCH -p kaxiras # Partition to submit to
#SBATCH --mem-per-cpu=7100 # Memory per cpu in MB (see also--mem)
#SBATCH -o job_%a.out # Standard out goes to this file
#SBATCH -e job_%a.err # Standard err goes to this file
##SBATCH --account=cs205


module load intel/17.0.4-fasrc01 
module load impi/2017.2.174-fasrc01
module list 


DIR=(*/)
cd ./${DIR[$SLURM_ARRAY_TASK_ID]} 
pwd
source params.conf
FILE='./CONTCAR'
if [[ -f "$FILE" ]]; then
    echo "VASP run already finished. Skip"
else 
    mpirun -n $SLURM_NTASKS $VASP_FILEPATH > vasp.out
fi 
