#!/bin/bash
#SBATCH --job-name=vasp_job
#SBATCH -n 4 # Number of cores requested
#SBATCH -t 1-00:00 # Runtime in minutes
#SBATCH -p shared # Partition to submit to
#SBATCH --mem-per-cpu=7100 # Memory per cpu in MB (see also--mem)
#SBATCH -o job_%j.out # Standard out goes to this file
#SBATCH -e job_%j.err # Standard err goes to this file
#SBATCH --account=cs205

source params.conf
mpirun -n $SLURM_NTASKS $VASP_FILEPATH
