#!/bin/bash
#SBATCH --job-name=gr
#SBATCH -n 1 # Number of cores requested
#SBATCH -t 8:00:00 # Runtime in minutes
#SBATCH -p shared,test # Partition to submit to
#SBATCH --mem-per-cpu=5000 # Memory per cpu in MB (see also--mem)
#SBATCH -o job.out # Standard out goes to this file
#SBATCH -e job.err # Standard err goes to this file
#SBATCH --account=cs205

module load intel/17.0.4-fasrc01 
module load impi/2017.2.174-fasrc01

module list

cp POSCAR_WSe2 POSCAR
phonopy --dim="2 2 1" -d -c POSCAR-unit # creates a structural file of the supercell and phonopy_disp.yaml (for phonon calculation in phonopy)

for ((i=1;i<=6;i=i+1));do
    mkdir phon_00$i
    cd phon_00$i 
    cp ../POSCAR-00$i POSCAR
    cp ../INCAR .
    cp ../KPOINTS .
    cp ../POTCAR .
    cp ../bat_vasp .
    sbatch bat_vasp
    cd ..
done;


